### ISSUE TITLE
Missing input descriptors.

### ISSUE THREAD

**Issue by Hedonium** [libretro/PokeMini#10]
https://github.com/libretro/PokeMini/blob/master/libretro/libretro.c#L99
https://github.com/libretro/PokeMini/blob/master/libretro/reference.c#L57

Would add them but don't want to break anything.

**Comment by jdgleaver** [comment]
Input descriptors were added in commit 2f8fa8ab9d35e9d05788aaa51560609f0cd2dbaf :smiley:
