### ISSUE TITLE
battery save is not working

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/PokeMini#4]
Is save a thing on this core? I can't save any game.

Btw, there should be a core option to chose either shared EEP or per game.

**Comment by Sanaki** [comment]
Both games can save fine, but you have to hit power (default controller binding is select) to make it write the save. Just verified.

**Comment by jdgleaver** [comment]
Oh wow! This is very exciting. I'll have a look later and see whether 'power off on close content' can be made the default behaviour.

**Comment by jdgleaver** [comment]
And now all games will save automatically: PR #32  :)
