### ISSUE TITLE
Make it upstream compatible

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/PokeMini#6]
Where's the 'platform' folder? libretro folder belongs there, please make it upstream friendly (JustBurn was open about a libretro port last time I talked to him).

**Comment by meepingsnesroms** [comment]
Would you like to takeover this core?
I am busy with PC98 and that is more important to me.

I ported it in 2 days because I was bored, not because I actually cared about the roms on the system, so my motivation for it is very low.
